acl_admin/acl_admin/urls.py
from django.contrib import admin
from django.conf.urls import include, url


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cms/',include('cms.urls', namespace='cms'))
]

acl_admin/cms/urls.py
from django.conf.urls import url
from cms import views

urlpatterns = [
    # ACL
    url(r'^acl/$', views.acl_list, name='acl_list'),   # 一覧
    url(r'^acl/add/$', views.acl_edit, name='acl_add'),  # 登録
    url(r'^acl/mod/(?P<vlan>\d+)/$', views.acl_edit, name='acl_mod'),  # 修正
    url(r'^acl/del/(?P<vlan>\d+)/$', views.acl_del, name='acl_del'),   # 削除
        ]

acl_admin/cms/models.py
from django.db import models

# Create your models here.
class ACL(models.Model):
    """Access_Control_List"""
    acl_id = models.IntegerField('acl_id', blank=True)
    vlan = models.IntegerFoeld('vlan',blank=True)
    acl = models.CharField('ACL', max_length=225)
    active = models.IntegerFoeld('active', blank=True,default=0)

    def __int__(self):
            return self.acl_id
        
    def __int__(self):
            return self.vlan
    
    def __int__(self):
            return self.active

acl_admin/cms/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

from cms.models import ACL


def acl_list(request):
    """ACLの一覧表示"""
#    return HttpResponse('ACL一覧')
    acls = ACL.objects.all().order_by('vlan')
    return render(request,
                  'cms/acl_list.html',
                  {'acls':acls}
                 )

def acl_edit(request,vlan=None):
    """ACLの編集"""
    return HttpResponse('ACLの編集')

def acl_del(request,vlan):
    """ACLの削除"""
    return HttpResponse('ACLの削除')

acl_admin/acl_admin/cms/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}Access Control List{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-2.2.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>

acl_admin/acl_admin/cms/templates/cms/acl_list.html
{% extends "base.html" %}

{% block title %}ACLの一覧{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 8px;
}
</style>
{% endblock %}

{% block content %}
    <h3 class="page-header">ACLの一覧</h3>
    <a href="{% url 'cms:acl_add' %}" class="btn btn-default btn-sm">追加</a>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>vlan名</th>
          <th>プロトコル</th>
          <th>送信元IP</th>
          <th>送信元ワイルドカードマスク</th>
          <th>送信元ポート番号</th>
          <th>宛先IP</th>
          <th>宛先ワイルドカードマスク</th>
          <th>宛先ポート番号</th>
        </tr>
      </thead>
      <tbody>
        {% for acl in acls %}
        <tr>
          <td>{{ acl.vlan }}</td>
          <td>{{ acl.protocol }}</td>
          <td>{{ acl.src_ip }}</td>
          <td>{{ acl.src_wc }}</td>          
          <td>{{ acl.src_port }}</td>
          <td>{{ acl.dst_ip }}</td>
          <td>{{ acl.dst_wc }}</td>
          <td>{{ acl.dst_port }}</td>
          <td>
            <a href="{% url 'cms:acl_mod' acl_id=acl.id %}" class="btn btn-default btn-sm">修正</a>
            <a href="{% url 'cms:acl_del' acl_id=acl.id %}" class="btn btn-default btn-sm">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>